baseurl = "http://iris-go.com/"
languageCode = "en-us"
title = "Iris - Documentation"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "kataras"
	description = "The fastest web framework."
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/kataras/iris"

	version = "4.0.0-alpha.5"
	logo = "images/logo.png"
	favicon = "images/favicon.ico"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "light green"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = "MakisMaropoulos"
	github  = "kataras"

[[menu.main]]
	name   = "Introduction"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Features"
	url    = "features/"
	weight = 10

[[menu.main]]
	name   = "Versioning"
	url    = "versioning/"
	weight = 20

[[menu.main]]
	name   = "Install"
	url    = "install/"
	weight = 30

[[menu.main]]
	name   = "Hi"
	url    = "hi/"
	weight = 40

[[menu.main]]
	name   = "Transport Layer Security"
	url    = "tls/"
	weight = 50

[[menu.main]]
	name   = "Handlers"
	url    = "handlers/"
	weight = 60

[[menu.main]]
	name   = "Middleware"
	url    = "middleware/"
	weight = 70

[[menu.main]]
	name   = "API"
	url    = "api/"
	weight = 80

[[menu.main]]
	name   = "Declaration"
	url    = "declaration/"
	weight = 90

[[menu.main]]
	name   = "Configuration"
	url    = "configuration/"
	weight = 100

[[menu.main]]
	name   = "Party"
	url    = "party/"
	weight = 110

[[menu.main]]
	name   = "Subdomains"
	url    = "subdomains/"
	weight = 120

[[menu.main]]
	name   = "Named Parameters"
	url    = "named_parameters/"
	weight = 130

[[menu.main]]
	name   = "Static Files"
	url    = "static_files/"
	weight = 140

[[menu.main]]
	name   = "Send Files"
	url    = "send_files/"
	weight = 150

[[menu.main]]
	name   = "Send e-mails"
	url    = "send_emails/"
	weight = 160

[[menu.main]]
	name   = "Render"
	url    = "render/"
	weight = 170

[[menu.main]]
	name   = "Gzip"
	url    = "gzip/"
	weight = 180

[[menu.main]]
	name   = "Streaming"
	url    = "streaming/"
	weight = 190

[[menu.main]]
	name   = "Cookies"
	url    = "cookies/"
	weight = 200

[[menu.main]]
	name   = "Flash Messages"
	url    = "flash_messages/"
	weight = 210

[[menu.main]]
	name   = "Body Binder"
	url    = "body_binder/"
	weight = 220

[[menu.main]]
	name   = "Custom Http Errors"
	url    = "custom_http_errors/"
	weight = 230

[[menu.main]]
	name   = "Context"
	url    = "context/"
	weight = 240

[[menu.main]]
	name   = "Logger"
	url    = "logger/"
	weight = 250

[[menu.main]]
	name   = "HTTP access control"
	url    = "http_access_control/"
	weight = 260

[[menu.main]]
	name   = "Basic Authentication"
	url    = "basic_authentication/"
	weight = 270

[[menu.main]]
	name   = "OAuth, OAuth2"
	url    = "oauth_oauth2/"
	weight = 280

[[menu.main]]
	name   = "JSON Web Tokens"
	url    = "jwt/"
	weight = 290

[[menu.main]]
	name   = "Secure"
	url    = "secure/"
	weight = 300

[[menu.main]]
	name   = "Sessions"
	url    = "sessions/"
	weight = 310

[[menu.main]]
	name   = "Websockets"
	url    = "websockets/"
	weight = 320

[[menu.main]]
	name   = "Graceful"
	url    = "graceful/"
	weight = 330

[[menu.main]]
	name   = "Recovery"
	url    = "recovery/"
	weight = 340

[[menu.main]]
	name   = "Plugins"
	url    = "plugins/"
	weight = 350


[[menu.main]]
	name   = "Internationalization and Localization"
	url    = "internationalization_and_localization/"
	weight = 360

[[menu.main]]
	name   = "Easy Typescript"
	url    = "typescript/"
	weight = 370

[[menu.main]]
	name   = "Browser based Editor"
	url    = "browser_based_editor/"
	weight = 380

[[menu.main]]
	name   = "Control panel"
	url    = "control_panel/"
	weight = 390

[[menu.main]]
	name   = "Examples"
	url    = "examples/"
	weight = 400

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true